# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-24 11:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defaultteam1', models.CharField(blank=True, default='', max_length=5)),
                ('defaultteam2', models.CharField(blank=True, default='', max_length=5)),
                ('date', models.BigIntegerField(blank=True, default=0)),
                ('stage', models.IntegerField(blank=True, default=0)),
                ('group', models.CharField(blank=True, max_length=5)),
                ('position', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.AlterModelOptions(
            name='team',
            options={},
        ),
        migrations.AddField(
            model_name='match',
            name='team1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team1', to='api.Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='team2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team2', to='api.Team'),
        ),
    ]
