# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 18:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0010_auto_20160425_1415'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupstageWinners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(blank=True, default=-1)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prono_groupstage_winners', to='api.Group')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prono_groupstage_winners', to='api.Team')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prono_groupstage_winners', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
