# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 19:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20160426_1857'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GroupstageWinners',
            new_name='PronoGroupstageWinners',
        ),
    ]
