# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_pronoteamresult_pronototalgoals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='groupstage_points',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
