# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20160427_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='groupstage_points',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
