# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_lastupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='displayname',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
