# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_userprofile_displayname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='iso_icon',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
