# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20160502_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.FileField(blank=True, default='', upload_to='avatars/'),
        ),
    ]
