# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20160502_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
