# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 21:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0021_auto_20160502_2052'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvatarUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, default='', upload_to='avatar/')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avatar_upload', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
