# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 22:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_avatarupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatarupload',
            name='file',
            field=models.FileField(blank=True, default='', upload_to='avatars/'),
        ),
    ]
